{
  "comments": [
    {
      "key": {
        "uuid": "7da0ccb5_a8039756",
        "filename": "factotum/factotum.go",
        "patchSetId": 1
      },
      "lineNbr": 81,
      "author": {
        "id": 5020
      },
      "writtenOn": "2017-02-07T00:20:23Z",
      "side": 1,
      "message": "I think this should be a panic",
      "revId": "f6727337d007c52228bd7b4c7dd472dc2caa33a1",
      "serverId": "0759ed4b-3fdc-34dc-866b-f2e708168c03",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "1f529216_20907dac",
        "filename": "factotum/factotum.go",
        "patchSetId": 1
      },
      "lineNbr": 85,
      "author": {
        "id": 5020
      },
      "writtenOn": "2017-02-07T00:20:23Z",
      "side": 1,
      "message": "this should be log.Debug or something\nit should also include context, as there\u0027s no clue what user it pertains to or even what package is raising this log message",
      "revId": "f6727337d007c52228bd7b4c7dd472dc2caa33a1",
      "serverId": "0759ed4b-3fdc-34dc-866b-f2e708168c03",
      "unresolved": true
    }
  ]
}